version: 2.1
pipelines: true
orbs:
  cypress: cypress-io/cypress@1.26.0
executors:
  base-12:
    docker:
      - image: cypress/base-12-18-3
    environment:
      LOCALSTACK_HOST: localhost
      LOCAL_ES_HOST: localhost
      CYPRESS_TESTING: true
      NODE_ENV: test

jobs:
  build:
    working_directory: ~/cumulus-dashboard
    docker:
      - image: cimg/node:12.18.0
    steps:
      - checkout


      - run:
          name: Install Dependencies
          command: |
            npm ci

      - run:
          name: Install Deps
          command: npm install xvfb

      - run:
          name: Run Audit-CI
          command: |
            npm run audit-ci

      - run:
          name: Build Dashboard
          command: |
              npm run build

      - run:
          name: Run Unit Tests
          command: |
              npm run test

      - setup_remote_docker:
          version: 19.03.13

      - cypress/run:
         executor: base-12
         store_artifacts: true
         start: 'npm run start-dashboard'
         wait-on: 'http://localhost:5001'

      # - run:
      #     name: Start the Dashboard
      #     command: |
      #       echo $(pwd) && \
      #       npm run start-dashboard


      # - run:
      #     name: Run Cypress Tests
      #     command: |
      #       npm run cypress-ci

      # - store_artifacts:
      #     path: ~/cumulus-dashboard/cypress/screenshots

      # - store_artifacts:
      #     path: ~/cumulus-dashboard/cypress/videos

  deploy:
    machine: true
    working_directory: ~/cumulus-dashboard
    steps:
      - checkout

      - run:
          name: Install AWSCLI
          command: sudo pip install awscli

      - run:
          name: Install Dependencies
          command: |
            export NVM_DIR="/opt/circleci/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            nvm install v12.18.0
            nvm alias default v12.18.0
            npm install -g npm
            npm ci --no-optional

      - run:
          # This has to be done in a separate step, like this, because Circle CI
          # will not interpolate values when setting environment variables
          name: Setup Sandbox Environment Variables
          command: |
            echo 'export AWS_ACCESS_KEY_ID="$SANDBOX_ACCESS_KEY_ID"' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY="$SANDBOX_SECRET_ACCESS_KEY"' >> $BASH_ENV

      - run:
          name: Build Sandbox Dist
          command: |
            docker run --rm \
              -v /home/circleci/.cache:/root/.cache \
              -v $(pwd):/home \
              --workdir /home \
              -e APIROOT=${SANDBOX_API} \
              node:12.18.0 \
              npm run build

      - run:
          name: Deploy to S3
          command: |
            aws s3 sync $(pwd)/dist s3://${SANDBOX_DASHBOARD_BUCKET}

      - run:
          # This has to be done in a separate step, like this, because Circle CI
          # will not interpolate values when setting environment variables
          name: Setup Sandbox Environment Variables
          command: |
            echo 'export AWS_ACCESS_KEY_ID="$SANDBOX_ACCESS_KEY_ID"' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY="$SANDBOX_SECRET_ACCESS_KEY"' >> $BASH_ENV

      - run:
          name: Build Sandbox Dist
          command: |
            docker run --rm \
              -v /home/circleci/.cache:/root/.cache \
              -v $(pwd):/home \
              --workdir /home \
              -e AWS_REGION=${SANDBOX_AWS_REGION} \
              -e APIROOT=${SANDBOX_API_ROOT} \
              node:12.18.0 \
              npm run build

      - run:
          name: Deploy to Cumulus Sandbox
          command: |
            aws s3 sync $(pwd)/dist s3://${SANDBOX_DASHBOARD_BUCKET}

      - run:
          # This has to be done in a separate step, like this, because Circle CI
          # will not interpolate values when setting environment variables
          name: Setup SIT Environment Variables
          command: |
            echo 'export AWS_ACCESS_KEY_ID="$SIT_ACCESS_KEY_ID"' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY="$SIT_SECRET_ACCESS_KEY"' >> $BASH_ENV

      - run:
          name: Build SIT Dist
          command: |
            docker run --rm \
              -v /home/circleci/.cache:/root/.cache \
              -v $(pwd):/home \
              --workdir /home \
              -e AWS_REGION=${SIT_AWS_REGION} \
              -e APIROOT=${SIT_API_ROOT} \
              node:12.18.0 \
              npm run build

      - run:
          name: Deploy to Cumulus SIT
          command: |
            aws s3 sync $(pwd)/dist s3://${SIT_DASHBOARD_BUCKET}

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: develop
