version: "3"
services:
  serve_api:
    image: cumuluss/cumuluslocalapi:4.0.0
    network_mode: "service:shim"
    depends_on:
      - localstack
      - elasticsearch
    working_dir:
      /cumulus-dashboard
    environment:
      - LOCALSTACK_HOST=localhost
      - LOCAL_ES_HOST=localhost
      - NODE_ENV=test
      - cmr_provider=CUMULUS
      - FAKE_AUTH=true
  shim:   # empty container to open ports
    image: alpine:latest
    command:
      tail -f /dev/null
    working_dir:
      /cumulus-dashboard
    ports:
      - "5001:5001"
